version: "3.8"
services:
    api:
        build: ./api
        command: yarn run start
        ports: 
            - 3000:3000
        depends_on: 
            - data
    data: 
        image: mongo:4.0.4
        ports:
            - 37521:27017
