version: "3.8"
services:
    api:
        build: ./api
        restart: always
        command: yarn run start
        ports: 
            - 3000:3000
        depends_on: 
            - data
    data: 
        image: mongo:4.0.4
        restart: always
        container_name: "mongo"
        ports:
            - 27017:27017
